import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import ContactSection from "../components/Section/Home/ContactSection";
import Contact from "../components/Section/Home/ContactSection";
import ExperienceSection from "../components/Section/Home/ExperienceSection";
import Footer from "../components/Footer";
import Header from "../components/Header";
import PresentationSection from "../components/Section/Home/PresentationSection";
import ProjectSection from "../components/Section/Home/ProjectSection";
import SkillsSection from "../components/Section/Home/SkillsSection";
import WelcomeSection from "../components/Section/Home/WelcomeSection";
import styles from "../styles/Home.module.css";
import { Experiences, Project, Skills } from "../types/types";
import { sanityClient } from "./../sanity";

interface props {
  projects: Project[];
  skills: Skills[];
  experiences: Experiences[];
}

export default function Home({ projects, skills, experiences }: props) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gb-color-black">
        <WelcomeSection />
        <PresentationSection />
        <ProjectSection projects={projects} />
        <SkillsSection skills={skills} />
        <ExperienceSection experiences={experiences} />
        <ContactSection />
        <Footer />
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const queryProjects = `
  *[_type == 'project']{
    title,
    url,
    githubRepository,
    slug,
    mainImage,
    "technologies": technologies[]->{title,descriptionIcon },
    body,
  }
  `;

  const querySkills = `
  *[_type == 'skills']{
    createdAt,
    skills,
    "technologies": technologies[]->{title,descriptionIcon },
  } | order(createdAt asc)
  `;

  const queryExperiences = `
  *[_type == 'experience']{
    date,
    company,
    post,
    description,
    createdAt,
    "technologies": technologies[]->{title,descriptionIcon },
  } | order(createdAt desc)
  `;

  const projects = await sanityClient.fetch(queryProjects);
  const skills = await sanityClient.fetch(querySkills);
  const experiences = await sanityClient.fetch(queryExperiences);

  return {
    props: {
      projects,
      skills,
      experiences,
    },
  };
};
