import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import PresentationSection from "../components/PresentationSection";
import ProjectSection from "../components/ProjectSection";
import WelcomeSection from "../components/WelcomeSection";
import styles from "../styles/Home.module.css";
import { sanityClient } from "./../sanity";

export default function Home({projects} : any) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gb-color-black">
        <WelcomeSection />
        <PresentationSection />
        <ProjectSection projects={projects}/>
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const query = `
  *[_type == 'project']{
    title,
    url,
    githubRepository,
    slug,
    mainImage,
    "technologies": technologies[]->{title,descriptionIcon },
    body,
  }
  `;

  const projects = await sanityClient.fetch(query);

  return {
    props: {
      projects,
    },
  };
};
