import { AnimatePresence } from "framer-motion";
import Head from "next/head";
import React, { useEffect } from "react";

import Title from "./../components/Library/Title";
import Header from "../components/Header";
import ProjectsHeader from "../components/Section/Projects/ProjectsHeader";
import { GetStaticProps } from "next";
import { Technology } from "../types/types";
import { sanityClient } from "../sanity";
import ProjectsSection from "../components/Section/Projects/ProjectsSection";

interface props {
 technologies: string[];
}

const projects = ({ technologies }: props) => {
 return (
  <div>
   <AnimatePresence>
    <Head>
     <title>Landeau Antonin</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.png" />
    </Head>
    <main className="bg-gb-color-black" key="animation">
     <Header />
     <ProjectsHeader />
     <ProjectsSection technologies={technologies} />
    </main>
   </AnimatePresence>
  </div>
 );
};

export const getStaticProps: GetStaticProps = async () => {
 const queryTechnologies = `*[_type == 'technology' ]{
  title
 }`;
 const technologies = await sanityClient.fetch(queryTechnologies);
 console.log(technologies);
 const technologyTitles = technologies.map(
  (technology: Technology) => technology.title
 );

 return {
  props: {
   technologies: technologyTitles,
  },
 };
};

export default projects;
